[package]
name = "detox-parser-manifest"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
detox-parser-core = { workspace = true }
sqlx = { version = "0.8", default-features = false, features = ["runtime-tokio", "tls-rustls", "postgres"] }
tracing = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
sqlx = { version = "0.8", default-features = false, features = ["runtime-tokio", "tls-rustls", "postgres"] }
